name: PR Checks

on:
  pull_request:
    branches:
      - master

jobs:
  check-script:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: "actions/checkout@v4"

      - name: Install Nix
        uses: "cachix/install-nix-action@v17"

      - name: Verify Script
        run: nix develop .#dev --command bash -c 'make check'

  check-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: "actions/checkout@v4"

      - name: Install Nix
        uses: "cachix/install-nix-action@v17"

      - name: Verify Release
        run: nix develop --command secrets version
