name: PR Validation

on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: nix develop .#dev --command bash -c 'make check'

      - name: Test
        run: nix develop --command secrets version
