name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write # grant permissions to create releases

jobs:
  check-script:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: "actions/checkout@v4"

      - name: Install Nix
        uses: "cachix/install-nix-action@v17"

      - name: Check Build
        run: nix develop .#dev --command bash -c 'make check'

  release:
    runs-on: ubuntu-22.04
    needs: check-script
    steps:
      - name: Checkout repository
        uses: "actions/checkout@v4"

      - name: Install Nix
        uses: "cachix/install-nix-action@v17"

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nix develop .#dev --command bash -c 'make release'
