name: Validate and Release

on:
  push:
    branches:
      - master

permissions:
  contents: write # grant permissions to create releases

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: nix develop .#dev --command bash -c 'make check'

      - name: Test
        run: nix develop --command secrets version

  release:
    name: Release
    needs: validate
    if: contains(github.event.head_commit.modified, 'VERSION')
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        run: VERSION="$(cat VERSION)" && echo "version=${VERSION}" >> "${GITHUB_OUTPUT}"

      - name: Check Release
        id: check_release
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          if [ -z "$(git tag -l "${TAG}")" ]; then
            echo "info: tag ${TAG} does not exist - proceeding with release ✅"
            exit 0
          else
            echo "error: tag ${TAG} already exists ❌"
            exit 1
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release v${{ steps.get_version.outputs.version }}"
          tag_name: "v${{ steps.get_version.outputs.version }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
          generate_release_notes: true
          make_latest: true
          prerelease: false
          draft: false
